version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Upload PDF to S3
          command: aws s3 cp resume.pdf s3://lpan-resume/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
